# Generated by Django 3.0.2 on 2020-03-15 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calc', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='feedback_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=7)),
                ('feedback', models.CharField(max_length=700)),
                ('userid', models.CharField(max_length=10)),
            ],
        ),
    ]
